# Default values for hcloud-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hetznercloud/hcloud-csi-driver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

storageClass:
  name: hcloud-volumes
  isDefault: true

secret:
  create: false
  name: hcloud-api-token
  hcloudApiToken:
  labels: {}
  annotations: {}
