{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-csi-driver.secretName" . }}
  labels:
    {{- include "hcloud-csi-driver.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{ toYaml .Values.secret.labels | indent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.secret.annotations }}
    {{ toYaml .Values.secret.annotations | indent 4 }}
    {{- end }}
stringData:
  token: "{{ .Values.secret.hcloudApiToken }}"
{{- end -}}
